name: Informe Diario PVPC

on:
  schedule:
    - cron: "09 17 * * *"   # Horario verano -1 hora, horario invierno -2 horas
    - cron: "0 20 * * *"    # 20:00 UTC ≈ 22:00 CEST
    - cron: "15 20 * * *"   # 20:15 UTC ≈ 22:15 CEST
    - cron: "30 20 * * *"   # 20:30 UTC ≈ 22:30 CEST
    - cron: "45 20 * * *"   # 20:45 UTC ≈ 22:45 CEST
    - cron: "0 21 * * *"    # 21:00 UTC ≈ 23:00 CEST
    - cron: "15 21 * * *"   # 21:15 UTC ≈ 23:15 CEST (margen hasta 23:30)
  workflow_dispatch:

jobs:
  pvpc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib pdfkit requests

      - name: Instalar wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Descargar JSON desde ESIOS
        env:
          ESIOS_TOKEN: ${{ secrets.ESIOS_TOKEN }}
        run: python descargar_json_ree.py

      - name: Generar PDF
        run: python generar_pdf.py

      - name: Enviar PDF por email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: python enviar_email.py

      - name: Subir PDF al repositorio (opcional)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add outputs/*.pdf || echo "No PDFs"
          git commit -m "PDF diario $(date +'%Y-%m-%d')" || echo "Sin cambios"
          git push
