name: Informe Diario PVPC

on:
  schedule:
    - cron: "47 15 * * *"   # Actual: 15:18 UTC. Opción alternativa: "0 19 * * *" para después de publicación (19:00 UTC ≈ 21:00 ES)
  workflow_dispatch:

jobs:
  pvpc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib pdfkit requests openpyxl

      - name: Instalar wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Descargar XLS desde REE
        run: python descargar_xls_ree.py

      - name: Convertir XLS a XLSX
        run: python convertir_xls_a_xlsx.py

      - name: Procesar XLSX a JSON
        run: python procesar_xlsx_a_json.py

      - name: Generar PDF
        run: python generar_pdf.py

      - name: Enviar PDF por email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: python enviar_email.py

      - name: Subir PDF al repositorio (opcional)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add outputs/*.pdf || echo "No PDFs"
          git commit -m "PDF diario $(date +'%Y-%m-%d')" || echo "Sin cambios"
          git push
