name: Informe Diario PVPC

on:
  schedule:
    - cron: "18 15 * * *"   # Se ejecuta todos los días a las 13:30 UTC (15:30 hora peninsular)
  workflow_dispatch:          # Permite lanzarlo manualmente

jobs:
  pvpc:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - uses: actions/checkout@v3

      # 2️⃣ Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3️⃣ Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib pdfkit requests openpyxl

      # 4️⃣ Instalar wkhtmltopdf (necesario para PDF)
      - name: Instalar wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      # 5️⃣ Descargar XLS desde REE
      - name: Descargar archivo XLS PVPC
        run: python descargar_xls_ree.py

      # 6️⃣ Generar PDF
      - name: Generar PDF
        run: python generar_pdf.py

      # 7️⃣ Enviar PDF por email
      - name: Enviar PDF por email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: python enviar_email.py

      # 8️⃣ Subir PDF al repositorio (opcional)
      - name: Subir PDF al repositorio
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add outputs/*.pdf || echo "No hay PDFs"
          git commit -m "PDF diario $(date +'%Y-%m-%d')" || echo "No hay cambios que subir"
          git push

